.\" ENVIRONMENTS:  ANSI
.TH "basic types" Definition "(Language/lexical elements/identifiers/types)"
.PC
.PP
The
.I "basic types"
are the integer and floating types.
These are the types that C defines, and they are all scalar
rather than aggregate.
All other types are constructed from the basic types.
.SH Cross-references
.nf
\*(AS, \*(PS3.1.2.5
\*(KR, p. 195
.SH "See Also"
.B
floating types, integer types, types
.R
