.\" ENVIRONMENTS: COHERENT, LC, TOS, ISIS, ANSI
.ds AS ANSI Standard
.ds KR The C Programming Language, Kernighan and Ritchie
.TH "enumeration constant" 7 2015 "(Lexical elements/constants)" Definition
.PC
.PP
An
.I "enumeration constant"
is a member of an enumeration.
.if \nX=4 \{\
Its syntax is as follows:
.DM
.PP
.nf
	enumeration-constant:
		identifier
.fi
.DE
.PP \}
This constant has type
.BR int .
.PP
For example, in the enumeration
.DM
.PP
.nf
	enum example { blue, green, yellow };
.fi
.DE
.PP
.B blue
is an enumeration constant.
.SH Cross-references
.nf
\*(AS, \*(PS3.1.3.3
\*(KR, pp. 39, 194
.SH "See Also"
.B
constants, enum
.R
