.\" ENVIRONMENTS: COHERENT, LC, TOS, ISIS, ANSI
.TH "external name" Definition "(Language/lexical elements/identifiers)" Definition
.PC
.PP
An
.I "external name"
is an identifier that has external linkage.
The number and range of characters that may form an external name
depends upon the implementation.
The minimum maximum for the length of an external name is six characters,
and an implementation is not obliged to recognize both upper-case and
lower-case characters.
An implementation may exceed these limits.
.SH Cross-references
.nf
\*(AS, \*(PS3.1.2
\*(KR, p. 35
.SH "See Also"
.B
identifiers, internal name, linkage
.R
